#!/usr/bin/env python3
"""Generate src/Hexwaste.Formats/Combat/CriticalTables.g.cs from fallout2-ce.

Ports the two critical-hit tables in reference/fallout2-ce/src/combat.cc
(gCriticalHitTables[19][9][6] and gPlayerCriticalHitTable[9][6]) — see
docs/phase9-research-report.md M2. We keep the five gameplay fields (P14): damageMultiplier, flags, massiveStat,
statMod, massiveFlags (the secondary "massive critical" stat-roll columns). Only
the two messageId columns are dropped. Flags resolve from obj_types.h DAM_*;
stats from stat.h STAT_* (-1 = no massive roll).

Run:  python3 tools/gen_critical_tables.py
This is the only place the table is transcribed; do not hand-edit the .g.cs.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "reference/fallout2-ce/src/combat.cc"
OUT = ROOT / "src/Hexwaste.Formats/Combat/CriticalTables.g.cs"

DAM = {
    "0": 0,
    "DAM_KNOCKED_OUT": 0x01, "DAM_KNOCKED_DOWN": 0x02,
    "DAM_CRIP_LEG_LEFT": 0x04, "DAM_CRIP_LEG_RIGHT": 0x08,
    "DAM_CRIP_ARM_LEFT": 0x10, "DAM_CRIP_ARM_RIGHT": 0x20,
    "DAM_BLIND": 0x40, "DAM_DEAD": 0x80, "DAM_HIT": 0x100,
    "DAM_CRITICAL": 0x200, "DAM_ON_FIRE": 0x400, "DAM_BYPASS": 0x800,
    "DAM_EXPLODE": 0x1000, "DAM_DESTROY": 0x2000, "DAM_DROP": 0x4000,
    "DAM_LOSE_TURN": 0x8000,
    "DAM_HIT_SELF": 0x10000, "DAM_LOSE_AMMO": 0x20000, "DAM_DUD": 0x40000,
    "DAM_HURT_SELF": 0x80000, "DAM_RANDOM_HIT": 0x100000, "DAM_CRIP_RANDOM": 0x200000,
}


# stat.h STAT_* ordering (S/P/E/C/I/A/L); -1 = no massive-critical stat roll.
STAT = {
    "-1": -1, "STAT_STRENGTH": 0, "STAT_PERCEPTION": 1, "STAT_ENDURANCE": 2,
    "STAT_CHARISMA": 3, "STAT_INTELLIGENCE": 4, "STAT_AGILITY": 5, "STAT_LUCK": 6,
}


def resolve_flags(expr: str) -> int:
    val = 0
    for tok in expr.split("|"):
        tok = tok.strip()
        if tok not in DAM:
            sys.exit(f"unknown flag token: {tok!r}")
        val |= DAM[tok]
    return val


def resolve_stat(tok: str) -> int:
    tok = tok.strip()
    if tok not in STAT:
        sys.exit(f"unknown stat token: {tok!r}")
    return STAT[tok]


def rows(body: str):
    # leaf rows are the innermost { ... } (no nested braces):
    # { damageMultiplier, flags, massiveStat, statMod, massiveFlags, msgId1, msgId2 }
    out = []
    for leaf in re.findall(r"\{([^{}]+)\}", body):
        parts = [p.strip() for p in leaf.split(",")]
        if len(parts) != 7:
            continue  # not a 7-field critical row
        out.append((int(parts[0]), resolve_flags(parts[1]),
                    resolve_stat(parts[2]), int(parts[3]), resolve_flags(parts[4])))
    return out


def cf_rows(body: str):
    # _cf_table leaf rows: { effect0, effect1, effect2, effect3, effect4 } — each a DAM_* flag
    # expression (may contain '|'); the 5 columns are the Luck-bucketed severity 0..4.
    out = []
    for leaf in re.findall(r"\{([^{}]+)\}", body):
        parts = [p.strip() for p in leaf.split(",")]
        if len(parts) != 5:
            continue
        out.append(tuple(resolve_flags(p) for p in parts))
    return out


def slice_array(lines, decl_substr):
    start = next(i for i, l in enumerate(lines) if decl_substr in l and "= {" in l)
    depth = 0
    for j in range(start, len(lines)):
        depth += lines[j].count("{") - lines[j].count("}")
        if depth == 0 and j > start:
            return "\n".join(lines[start:j + 1])
    sys.exit(f"could not bound array {decl_substr}")


def fnv1a(values) -> int:
    h = 0xCBF29CE484222325
    for v in values:
        for b in str(v).encode() + b",":
            h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def emit(name, data, dims):
    lines = [f"    internal static readonly int[] {name} =", "    {"]
    flat = [x for row in data for x in row]  # 5-tuples flattened
    for i in range(0, len(flat), 15):  # 3 rows per line (5 fields each)
        lines.append("        " + ", ".join(str(x) for x in flat[i:i + 15]) + ",")
    lines.append("    };")
    return "\n".join(lines)


def main():
    text = SRC.read_text()
    lines = text.split("\n")
    critter = rows(slice_array(lines, "gCriticalHitTables["))
    player = rows(slice_array(lines, "gPlayerCriticalHitTable["))
    critfail = cf_rows(slice_array(lines, "_cf_table["))

    assert len(critter) == 19 * 9 * 6, f"critter rows {len(critter)} != 1026"
    assert len(player) == 9 * 6, f"player rows {len(player)} != 54"
    assert len(critfail) == 7, f"crit-failure rows {len(critfail)} != 7"

    checksum = fnv1a([x for r in critter + player + critfail for x in r])

    out = f"""// <auto-generated>
//   Generated by tools/gen_critical_tables.py from
//   reference/fallout2-ce/src/combat.cc gCriticalHitTables / gPlayerCriticalHitTable.
//   DO NOT EDIT BY HAND. Re-run the generator to update.
//   Stored fields (stride 5): damageMultiplier, flags, massiveStat, statMod,
//   massiveFlags (DAM_* from obj_types.h, STAT_* from stat.h). The two messageId
//   columns are dropped (P14).
// </auto-generated>
namespace Hexwaste.Formats.Combat;

public static partial class CriticalTables
{{
    public const int KillTypeCount = 19;
    public const int LocationCount = 9;
    public const int SeverityCount = 6;

    /// <summary>_cf_table dimensions (combat.cc): 7 weapon critical-failure-type rows × 5
    /// Luck-bucketed severity columns. The flat array is [failureType*5 + effect].</summary>
    public const int CritFailTypeCount = 7;
    public const int CritFailEffectCount = 5;

    /// <summary>Stride of one critical row: mult, flags, massiveStat, statMod, massiveFlags.</summary>
    public const int Stride = 5;

    /// <summary>FNV-1a over every field — guards the data file.</summary>
    public const ulong DataChecksum = 0x{checksum:016X}UL;

    // [(killType*LocationCount + location)*SeverityCount + severity] * Stride
    //   → {{mult, flags, massiveStat, statMod, massiveFlags}}
{emit("CritterData", critter, None)}

    // [(location)*SeverityCount + severity] * Stride (defender = the dude)
{emit("PlayerData", player, None)}

    // _cf_table[failureType*CritFailEffectCount + effect] → the DAM_* flags of a critical FAILURE
    //   (the attacker's fumble); failureType = weapon criticalFailureType, effect = Luck severity 0..4.
{emit("CritFailTable", critfail, None)}
}}
"""
    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(ROOT)}: critter={len(critter)} player={len(player)} "
          f"checksum=0x{checksum:016X}")


if __name__ == "__main__":
    main()
