#!/usr/bin/env python3
"""Generate PerkTable.g.cs from fallout2-ce src/perk.cc gPerkDescriptions (P28-M2).

The 119-entry perk table is a hardcoded array literal in perk.cc (like the critical
tables in combat.cc). This parses each `{ nullptr, nullptr, frmId, maxRank, minLevel,
stat, statModifier, param1, value1, paramMode, param2, value2, S,P,E,C,I,A,L }` row and
emits a checked-in C# table guarded by an FNV-1a checksum, mirroring tools/gen_critical_tables.py.

Usage:  python3 tools/gen_perk_table.py
Reads:  reference/fallout2-ce/src/perk.cc
Writes: src/Hexwaste.Formats/Perks/PerkTable.g.cs
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "reference/fallout2-ce/src/perk.cc"
OUT = ROOT / "src/Hexwaste.Formats/Perks/PerkTable.g.cs"

def fnv1a(data: bytes) -> int:
    h = 0x811c9dc5
    for b in data:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h

def main():
    text = SRC.read_text(encoding="latin-1")
    m = re.search(r"gPerkDescriptions\[PERK_COUNT\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m:
        sys.exit("could not find gPerkDescriptions array in perk.cc")
    body = m.group(1)

    def parse_field(tok):
        # a C int literal, possibly a bitwise OR of hex/decimal terms (gvar gate: N | 0x4000000).
        val = 0
        for part in tok.split("|"):
            val |= int(part.strip(), 0)  # base 0 handles 0x.., decimal, and leading '-'
        return val

    rows = []
    for line in re.findall(r"\{\s*nullptr\s*,\s*nullptr\s*,([^}]*)\}", body):
        nums = [parse_field(t) for t in line.split(",") if t.strip()]
        if len(nums) != 17:  # frmId..value2 (10) + stats[7]
            sys.exit(f"unexpected field count {len(nums)} in row: {line!r}")
        rows.append(nums)

    if not rows:
        sys.exit("parsed zero perk rows")

    # checksum over the flattened integer stream — any drift trips PerkTableTests.
    flat = ",".join(str(n) for row in rows for n in row)
    checksum = fnv1a(flat.encode())

    lines = []
    lines.append("// <auto-generated> by tools/gen_perk_table.py — DO NOT EDIT.")
    lines.append("// Ported from fallout2-ce src/perk.cc gPerkDescriptions (P28-M2).")
    lines.append("namespace Hexwaste.Formats.Perks;")
    lines.append("")
    lines.append("public static partial class PerkTable")
    lines.append("{")
    lines.append(f"    public const int Count = {len(rows)};")
    lines.append(f"    public const uint Checksum = 0x{checksum:08X}u;")
    lines.append("")
    lines.append("    // FrmId, MaxRank, MinLevel, Stat, StatModifier, Param1, Value1, ParamMode, Param2, Value2, [S,P,E,C,I,A,L]")
    lines.append("    internal static readonly PerkData[] Entries =")
    lines.append("    [")
    for i, r in enumerate(rows):
        frm, mr, ml, st, sm, p1, v1, pm, p2, v2 = r[:10]
        reqs = r[10:17]
        lines.append(f"        new({i}, {frm}, {mr}, {ml}, {st}, {sm}, {p1}, {v1}, {pm}, {p2}, {v2}, [{', '.join(map(str, reqs))}]),")
    lines.append("    ];")
    lines.append("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(rows)} perks, checksum 0x{checksum:08X}")

if __name__ == "__main__":
    main()
